name: lightdm_webkit_theme_litarvan
description: Litarvan's LightDM theme (uses Webkit2 Greeter)
version: 2.0.4
homepage: https://github.com/Litarvan/lightdm-webkit-theme-litarvan
author: Litarvan <adrien1975@live.fr>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular2: '>=2.2.0 <2.3.0'

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  js: ^0.6.0

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
